- src/main/scala/com/metamx/tranquility/storm/BeamBolt.scala
We send over 100k events per minute so this is polluting our log files.
> This is polluting our logs.

- src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- src/main/scala/com/metamx/tranquility/finagle/FinagleRegistry.scala
- src/main/scala/com/metamx/tranquility/finagle/FinagleRegistryConfig.scala
I already had this code change pending so I figured I'd make a pull request for it.  I tried 0.3.4 but setting it to false actually made things worse (retries cause new peons to fill up middle managers), so at this time I think it is probably best to leave the default fail fast as True.
> Making fail fast mode for finagle configurable

- README.md
It's the same as the previous stable (0.4.2) with some changes to packaging
and one code change: b22d8b14.
I think the changes are pretty low risk but it would still be cool if someone has the
opportunity to try this artifact out before merging this PR.
> Mark io.druid artifact stable.

- src/main/scala/com/metamx/tranquility/druid/DruidBeam.scala
- src/main/scala/com/metamx/tranquility/typeclass/JavaObjectWriter.scala
- src/main/scala/com/metamx/tranquility/typeclass/JsonWriter.scala
- src/main/scala/com/metamx/tranquility/typeclass/ObjectWriter.scala
- src/test/java/com/metamx/tranquility/javatests/StormJavaApiTest.java
- src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
Add option to extend contentType. 
Can be used to send data to druid in smile format.
> Add contentType as parameter

- build.sbt
This gets rid of all the samza 2.11 jars: sources, javadocs, etc.
After this I am pretty sure only the jars we want to get published will get published.
```
tranquility-core_2.10-javadoc.jar
tranquility-core_2.10-sources.jar
tranquility-core_2.10-tests.jar
tranquility-core_2.10.jar
tranquility-core_2.10.pom
tranquility-core_2.11-javadoc.jar
tranquility-core_2.11-sources.jar
tranquility-core_2.11-tests.jar
tranquility-core_2.11.jar
tranquility-core_2.11.pom
tranquility-samza_2.10-javadoc.jar
tranquility-samza_2.10-sources.jar
tranquility-samza_2.10.jar
tranquility-samza_2.10.pom
tranquility-storm_2.10-javadoc.jar
tranquility-storm_2.10-sources.jar
tranquility-storm_2.10.jar
tranquility-storm_2.10.pom
tranquility-storm_2.11-javadoc.jar
tranquility-storm_2.11-sources.jar …
```
> Nix extraneous samza jars for 2.11

- core/src/main/scala/com/metamx/tranquility/beam/ClusteredBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/test/scala/com/metamx/tranquility/test/ClusteredBeamTest.scala
This should make the time partitioning stuff work even if the user's timezone
is something other than UTC, or if the Timekeeper or Timestamper return
non-UTC times.
> Use UTC DateTimes and Intervals whenever making decisions involving segments.

- README.md
Tweaked the README to make it obvious what sort of data is expected to be sent via the `druidService`.
> Supply sample events in Tranquility README

- core/src/main/scala/com/metamx/tranquility/beam/MergingPartitioningBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidRollup.scala
- core/src/main/scala/com/metamx/tranquility/partition/GenericTimeAndDimsPartitioner.scala
- core/src/main/scala/com/metamx/tranquility/partition/HashCodePartitioner.scala
- core/src/main/scala/com/metamx/tranquility/partition/Partitioner.scala
- core/src/main/scala/com/metamx/tranquility/typeclass/Timestamper.scala
- core/src/test/java/com/metamx/tranquility/javatests/JavaApiTest.java
- core/src/test/scala/com/metamx/tranquility/test/DruidRollupTest.scala
- core/src/test/scala/com/metamx/tranquility/test/GenericTimeAndDimsPartitionerTest.scala
- core/src/test/scala/com/metamx/tranquility/test/HashPartitionBeamTest.scala
The default partitioning only works properly for Maps because other types are actually opaque
to tranquility (it doesn't know how the ObjectWriter is going to serialize them). But, you can
provide your own Partitioner (or an entire beamMergeFn, which you could already do).
Fixes #6.
> Rollup-aware partitioning by default for Maps, and a Partitioner interface for other types.

- spark/src/main/scala/com/metamx/tranquility/spark/BeamFactory.scala
- spark/src/main/scala/com/metamx/tranquility/spark/BeamRDD.scala
This should allow sending larger RDDs.
> Spark: Send using a Tranquilizer to avoid RDD materialization.

- build.sbt
This will hopefully fix some linking errors people have been reporting with
Hadoop and Spark. At least with this version we will be no worse off than
Druid itself.
Fixes #76 (I hope)
> Downgrade Jackson to match the version in Druid.

- core/src/main/scala/com/metamx/tranquility/beam/Beam.scala
- core/src/main/scala/com/metamx/tranquility/beam/BeamPacketizer.scala
- core/src/main/scala/com/metamx/tranquility/beam/ClusteredBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/HttpBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/MemoryBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/MergingPartitioningBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/NoopBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/RoundRobinBeam.scala
- core/src/main/scala/com/metamx/tranquility/beam/TransformingBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/finagle/BeamService.scala
- core/src/main/scala/com/metamx/tranquility/tranquilizer/Tranquilizer.scala
- core/src/test/scala/com/metamx/tranquility/test/BeamPacketizerTest.scala
- core/src/test/scala/com/metamx/tranquility/test/ClusteredBeamTest.scala
- core/src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
- core/src/test/scala/com/metamx/tranquility/test/HashPartitionBeamTest.scala
- core/src/test/scala/com/metamx/tranquility/test/TranquilizerTest.scala
- server/src/test/scala/com/metamx/tranquility/server/ServerDruidTest.scala
- server/src/test/scala/com/metamx/tranquility/server/TranquilityServletTest.scala
- storm/src/main/scala/com/metamx/tranquility/storm/TridentBeamState.scala
- storm/src/test/scala/com/metamx/tranquility/test/StormBoltTest.scala
Add Beam.sendBatch (returns a BitSet of successes), fixes #56.
Also:
- Deprecate Beam.propagate
- Make Tranquilizer's MessageDroppedException a singleton
- Improve ClusteredBeam tests and add tests involving dropping events
> Add Beam.sendBatch (returns a BitSet of successes)

- server/src/main/scala/com/metamx/tranquility/server/http/ServerMain.scala
- server/src/test/scala/com/metamx/tranquility/server/ServerMainTest.scala
Real arg parsing is probably a better idea than reading `args(0)`.
> Server: Switch to real arg parsing, and rename Main to ServerMain.

- README.md
- build.sbt
- core/src/main/scala/com/metamx/tranquility/config/ConfigHelper.scala
- core/src/main/scala/com/metamx/tranquility/config/config.scala
- core/src/test/resources/tranquility-core.yaml
- core/src/test/scala/com/metamx/tranquility/test/ConfigHelperTest.scala
- docs/kafka.md
- kafka/src/main/java/com/metamx/tranquility/kafka/KafkaConsumer.java
- kafka/src/main/java/com/metamx/tranquility/kafka/Main.java
- kafka/src/main/java/com/metamx/tranquility/kafka/model/MessageCounters.java
- kafka/src/main/java/com/metamx/tranquility/kafka/model/TranquilityKafkaConfig.java
- kafka/src/main/java/com/metamx/tranquility/kafka/writer/TranquilityEventWriter.java
- kafka/src/main/java/com/metamx/tranquility/kafka/writer/WriterController.java
- kafka/src/main/resources/logback.xml
- kafka/src/test/java/com/metamx/tranquility/kafka/KafkaConsumerTest.java
- kafka/src/test/java/com/metamx/tranquility/kafka/writer/WriterControllerTest.java
- kafka/src/universal/conf/tranquility-kafka.yaml.example
- server/src/main/scala/com/metamx/tranquility/server/config.scala
- server/src/main/scala/com/metamx/tranquility/server/http/ServerMain.scala
- server/src/test/scala/com/metamx/tranquility/server/ServerConfigTest.scala
This PR adds a module to Tranquility to help push data from Kafka into the indexing service through Tranquility. Multiple instances of tranquility-kafka can be run at the same time to provide scalability and high availability, and an instance can read from multiple Kafka topics and write to multiple Druid datasources. Tranquility-kafka supports regex pattern based mapping of Kafka topic to a Druid ingestion spec, thus allowing indexing tasks for new datasources to be automatically created when a new Kafka topic is created that matches the regex. If additional Kafka topic -> ingestion spec mappings need to be added, tranquility-kafka supports rolling updates without data loss.
To build, run: `sbt universal:packageZipTarball`
Unpack the tgz in …
> tranquility-kafka module

- README.md
- build.sbt
- docs/flink.md
- flink/src/main/scala/com/metamx/tranquility/flink/BeamFactory.scala
- flink/src/main/scala/com/metamx/tranquility/flink/BeamSink.scala
- flink/src/test/scala/com/metamx/tranquility/test/FlinkDruidTest.scala
This module adds support for Apache Flink. Works and looks a lot like the Spark module. But instead of the `BeamRDD` it contains `BeamSink`.
Had some struggle with the Flink dependency imports since they are not following the Scala naming conventions.
Would be great to get some feedback on this and even greater to get it merge.
> Apache Flink module

- core/src/main/scala/com/metamx/tranquility/config/ConfigHelper.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidTuning.scala
- core/src/test/resources/tranquility-core-no-tuningConfig.json
- core/src/test/scala/com/metamx/tranquility/test/ConfigHelperTest.scala
- distribution/src/universal/conf/kafka.json.example
- distribution/src/universal/conf/kafka.yaml.example
- distribution/src/universal/conf/server.json.example
- distribution/src/universal/conf/server.yaml.example
- docs/kafka.md
- docs/server.md
- No longer require "ioConfig", and remove it from the examples.
- Point out in the docs that either JSON or YAML is ok. Add sample configs and tests for JSON.
- Add tests for tuningConfig defaults.
> Changes to make configuration files easier to use.

- build.sbt
- kafka/src/test/java/com/metamx/tranquility/kafka/KafkaConsumerTest.java
Tested against Kafka 0.9 brokers and seems to work well. Fixes #108.
> tranquility-kafka: switch to kafka 0.8.2.2 for compatibility

- core/src/main/scala/com/metamx/tranquility/tranquilizer/SimpleTranquilizerAdapter.scala
- core/src/main/scala/com/metamx/tranquility/tranquilizer/Tranquilizer.scala
- core/src/test/scala/com/metamx/tranquility/test/TranquilizerTest.scala
> Tranquilizer.flush() to make batch / micro-batch oriented workflows easier

- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/druid/IndexService.scala
I think this should fix the issue reported in https://groups.google.com/d/topic/druid-development/nCMp7JCNhuo/discussion
> IndexService: close should return a future, and should not attempt to close a client that has not been created yet.

- docs/spark.md
- spark/src/main/scala/com/metamx/tranquility/spark/BeamFactory.scala
- spark/src/main/scala/com/metamx/tranquility/spark/BeamRDD.scala
- spark/src/test/scala/com/metamx/tranquility/test/SparkDruidTest.scala
> Spark: Recommend using singleton Beam.

- build.sbt
Otherwise you get:
[error] javadoc: error - invalid flag: -target
> Fix javadoc generation by restricting javacOptions to "compile".

- core/src/main/scala/com/metamx/tranquility/finagle/FinagleRegistryConfig.scala
Fixes #50
since our groups all just have one host in them, according to https://twitter.github.io/finagle/guide/Clients.html#client-fail-fast we should disable fail-fast.
> Disable Finagle fail-fast behavior by default.

- core/src/main/scala/com/metamx/tranquility/druid/TaskClient.scala
Should have been the task status, not the Finagle client status.
> Fix 'Loss of Druid redundancy' alert 'status' field.

- distribution/src/universal/conf/server.json.example
- docs/server.md
- server/src/main/scala/com/metamx/tranquility/server/PropertiesBasedServerConfig.scala
Jetty uses up to 8 threads for internal use (scaling based on number of processors), so
we need more than 8 threads to work on larger boxes. Higher default shouldn't be too bad
in general, so let's go with 40.
> Server: Raise default http.threads.

- core/src/main/scala/com/metamx/tranquility/beam/MessageHolder.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/test/resources/benchmark.json
- core/src/test/scala/com/metamx/tranquility/benchmark/BenchmarkMain.scala
- core/src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
- core/src/test/scala/com/metamx/tranquility/test/DruidBeamTest.scala
- core/src/test/scala/com/metamx/tranquility/test/TranquilityConfigTest.scala
- storm/src/test/java/com/metamx/tranquility/javatests/StormJavaApiTest.java
~130% speedup in BenchmarkMain (150k/sec -> 350k/sec on my machine.)
Also add a benchmark class (in a separate commit).
> Cache timestamps when using DruidBeams.fromConfig.

- core/src/main/scala/com/metamx/tranquility/tranquilizer/Tranquilizer.scala
- core/src/test/scala/com/metamx/tranquility/test/TranquilizerTest.scala
- docs/configuration.md
- docs/server.md
- server/src/main/scala/com/metamx/tranquility/server/http/TranquilityServlet.scala
- server/src/test/scala/com/metamx/tranquility/server/ServerTestUtil.scala
- server/src/test/scala/com/metamx/tranquility/server/TranquilityServletTest.scala
- Tranquilizer: Add blockOnFull flag to control behavior when outgoing queue is full.
- Server: Add async api.
Fixes #87
> Tranquilizer blockOnFull option, Server async api

- core/src/main/scala/com/metamx/tranquility/config/PropertiesBasedConfig.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamConfig.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidEnvironment.scala
- core/src/main/scala/com/metamx/tranquility/druid/IndexService.scala
- core/src/main/scala/com/metamx/tranquility/druid/OverlordLocator.scala
- core/src/main/scala/com/metamx/tranquility/druid/TaskLocator.scala
- core/src/main/scala/com/metamx/tranquility/finagle/DruidTaskResolver.scala
- core/src/main/scala/com/metamx/tranquility/finagle/FinagleRegistry.scala
- core/src/test/resources/example.json
- core/src/test/scala/com/metamx/tranquility/benchmark/BenchmarkMain.scala
- core/src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
- docs/configuration.md
Requires druid-io/druid#2419
This is enabled by setting druidBeam.taskLocator=overlord, and works by polling the
overlord in a background thread. Also added a useless setting for
druidBeam.overlordLocator, which might not be useless in the future if we ever have
a way to do that without Curator discovery (perhaps a hard-coded list, or a DNS name).
No integration tests yet, since the Druid code that enables this is not yet in a
Maven release so we cannot pull it in.
> Optionally locate Druid tasks through "runningTasks" endpoint on the overlord.

- build.sbt
- flink/src/test/scala/com/metamx/tranquility/test/FlinkDruidTest.scala
This PR updates flink-tranquility to use the latest Flink version. 
Fortunately they use proper naming for Scala versions now.
> Update to Flink 1.0.0

- core/src/test/resources/benchmark.json
Increasing lingerMillis to absurd heights has the effect of forcing all the work
onto the benchmarking thread, rather than allowing some of the work to occur
in the background send thread.
> Make benchmark more honest.

- core/src/main/scala/com/metamx/tranquility/finagle/DruidTaskResolver.scala
This message is logged frequently and can get annoying. The "location
changed" messages remain at INFO level.
> DruidTaskResolver: Demote polling log message to DEBUG.

- core/src/main/scala/com/metamx/tranquility/druid/IndexService.scala
We faced that sometimes druid returns 4xx error code, but we can't figure out why. It would be nice to have the uri and response body in logs for further investigation of non-retryable error.
> Additional logging for non-retryable responses

- core/src/main/scala/com/metamx/tranquility/config/PropertiesBasedConfig.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/test/resources/direct-druid-test.yaml
- core/src/test/resources/druid-broker.properties
- core/src/test/resources/druid-coordinator.properties
- core/src/test/resources/druid-overlord.properties
- core/src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
> DruidBeams: Respect druid.discovery.curator.path in fromConfig.

- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamMaker.scala
- core/src/test/scala/com/metamx/tranquility/test/DruidBeamTest.scala
This, combined with the runningTasks taskLocator, means that the cycleBucket
hack will eventually not be used anymore.
> DruidBeamMaker: Use availabilityGroup no longer tied to baseFirehoseId.

- .gitignore
- build.sbt
- core/src/test/java/org/apache/logging/log4j/core/LifeCycle.java
- core/src/test/java/org/apache/logging/log4j/core/util/Cancellable.java
- core/src/test/java/org/apache/logging/log4j/core/util/ShutdownCallbackRegistry.java
- core/src/test/resources/druid-overlord.properties
- core/src/test/scala/com/metamx/tranquility/test/DirectDruidTest.scala
- core/src/test/scala/com/metamx/tranquility/test/DruidBeamTest.scala
- core/src/test/scala/com/metamx/tranquility/test/DruidGuicerTest.scala
- docs/configuration.md
> Update to druid-0.9.0.

- build.sbt
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
see issue #190 
Some warnings of _type erasure_ are mentioned by compiler, seems ok. Tested with local kafka+tranquility+druid, any suggestion to write a reasonable test ?
> [Fix] Remove data type and InputRowParser type bindings

- build.sbt
- core/src/main/scala/com/metamx/tranquility/config/PropertiesBasedConfig.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeam.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeamConfig.scala
- core/src/main/scala/com/metamx/tranquility/druid/DruidBeams.scala
- core/src/main/scala/com/metamx/tranquility/druid/IndexService.scala
- core/src/main/scala/com/metamx/tranquility/security/BasicAuthClientMaker.scala
- core/src/main/scala/com/metamx/tranquility/security/SSLContextMaker.scala
- docs/configuration.md
- docs/server.md
- server/src/main/scala/com/metamx/tranquility/server/PropertiesBasedServerConfig.scala
- server/src/main/scala/com/metamx/tranquility/server/http/ServerMain.scala
This PR adds support for Basic HTTP authentication when Tranquility communicates with Druid.
The PR also adds configuration options that allow Tranquility Server to accept requests with TLS and communicate with a TLS-enabled Druid cluster.
> Support Basic HTTP auth with druid, TLS support for server
